#mysql
spring:
  datasource:
    #mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.160.240:3306/restaurant?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yyh.restaurant.bean

server:
  port: 9000




